 spring: 
    application:
        name: emprestimo-service
    datasource:
        url: jdbc:mysql://localhost:3306/biblioteca 
        username: root
        password:
    jpa:
        hibernate:
            ddlAuto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        showSql: true
 server:
  port: 6062
  
 eureka:
    client:
        serviceUrl: 
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

        
   
    
        
